### ISSUE TITLE
Failing to install with node@v10.24.0 & npm@5.8.0

### ISSUE THREAD

**Issue by arthurlutz** [urbiworx/node-red-contrib-midi#13]
```
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.24.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node',
6 verbose cli   '/usr/bin/npm',
6 verbose cli   'install',
6 verbose cli   '--no-audit',
6 verbose cli   '--no-update-notifier',
6 verbose cli   '--no-fund',
6 verbose cli   '--save',
6 verbose cli   '--save-prefix=~',
6 verbose cli   '--production',
6 verbose cli   'node-red-contrib-midi@1.0.1' ]
7 info using npm@5.8.0
8 info using node@v10.24.0
9 verbose npm-session 12b34d140e4026ec
10 silly install loadCurrentTree
11 silly install readLocalPackageData
12 verbose stack TypeError: glob.hasMagic is not a function
12 verbose stack     at Function.rimrafSync [as sync] (/usr/lib/nodejs/rimraf/rimraf.js:273:36)
12 verbose stack     at /usr/share/npm/lib/npm.js:328:20
12 verbose stack     at /usr/lib/nodejs/once.js:17:15
12 verbose stack     at Glob.<anonymous> (/usr/lib/nodejs/glob.js:100:7)
12 verbose stack     at Glob.emit (events.js:198:13)
12 verbose stack     at Glob.next (/usr/lib/nodejs/glob.js:357:10)
12 verbose stack     at Glob._processEmitQueue (/usr/lib/nodejs/glob.js:322:12)
12 verbose stack     at Glob.emitMatch (/usr/lib/nodejs/glob.js:302:8)
12 verbose stack     at Glob._finish (/usr/lib/nodejs/glob.js:242:8)
12 verbose stack     at Glob.<anonymous> (/usr/lib/nodejs/glob.js:195:27)
12 verbose stack     at Glob.cb (/usr/lib/nodejs/glob.js:380:11)
12 verbose stack     at Glob.<anonymous> (/usr/lib/nodejs/glob.js:544:17)
12 verbose stack     at Glob._afterReaddir (/usr/lib/nodejs/glob.js:708:15)
12 verbose stack     at go$readdir$cb (/usr/lib/nodejs/graceful-fs/graceful-fs.js:149:14)
12 verbose stack     at FSReqWrap.args [as oncomplete] (fs.js:140:20)
13 verbose cwd /home/pi/.node-red
14 verbose Linux 5.10.17-v7+
15 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-audit" "--no-update-notifier" "--no-fund" "--save" "--save-prefix=~" "--production" "node-red-contrib-midi@1.0.1"
16 verbose node v10.24.0
17 verbose npm  v5.8.0
18 error glob.hasMagic is not a function
19 verbose exit [ 1, true ]

```

libasound2-dev is installed (tried to read the other issues here before posting the issue here.

**Comment by kltv21** [comment]
node.js   uninstall    // 


node-v16.15.0-x64.msi    //node.js install

**Comment by natcl** [comment]
Indeed node 10 is not supported anymore.
